name: Terraform Destroy Infrastructure

on:
  workflow_dispatch:   # <-- Manual trigger only

jobs:
  destroy:
    name: Destroy Terraform Resources
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      ENV_NAME: ${{ github.event.inputs.environment || 'dev' }}


    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init -backend-config="key=${{ env.ENV_NAME }}/terraform.tfstate"

    - name: Terraform Plan Destroy
      run: terraform plan -destroy -var-file=env/${{ env.ENV_NAME }}/main.tfvars -out=destroy-tfplan

    - name: Wait for Manual Approval (for Destroy)
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.GITHUB_TOKEN }}
        approvers: rajmohanbtheteacher
        instructions: "This will destroy all resources for ${{ env.ENV_NAME }}. Confirm carefully!"

    - name: Terraform Apply Destroy Plan
      if: success()
      run: terraform apply destroy-tfplan
